# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-index-html
data:
  index.html: |
    Ini tampilan dari HTTPD dan nama saya Hendi Irwanto.
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-httpd
  labels:
    app: simple-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-httpd
  template:
    metadata:
      labels:
        app: simple-httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: httpd-html-volume
          mountPath: /usr/local/apache2/htdocs/index.html
          subPath: index.html
      volumes:
      - name: httpd-html-volume
        configMap:
          name: httpd-index-html
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: simple-httpd-service
spec:
  type: NodePort
  selector:
    app: simple-httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
